### PR TITLE
Support xunit2

### PR DESCRIPTION
**Pull request by jhamm**

### CODE REVIEW

**Comment by jhamm** [comment]
This PR is related to #86 

I am not sure if I can do anything to resolve the conflicts in the PR. If I can, please let me know.

**Comment by kurtschelfthout** [comment]
Thanks - will hopefully be able to deal with this tonight - if not it will be next week as I'm out for the weekend (just managing expectations ;) ). 
I'll probably add it to a separate branch for now until the kinks are worked out.

**Comment by jhamm** [comment]
Thanks for letting me know the plan :smile: 
I agree that adding the changes on a separate branch is a good idea.

**Comment by jhamm** [comment]
I was not able to build the FsCheck.Test project without adding the "Y" to the XCOPY command, but this appears to break the Travis-CI build. AppVeyor was able to build.

1) Building /home/travis/build/fsharp/FsCheck/FsCheck-mono.sln failed with exitcode 1.
2) : /usr/lib/mono/4.5/Microsoft.Common.targets(0,0): Command 'xcopy /SY /home/travis/build/fsharp/FsCheck/tests/FsCheck.Test/../../packages/xunit.runner.visualstudio /home/travis/build/fsharp/FsCheck/tests/FsCheck.Test/../../packages/xunit.runner.visualstudio.2.0.0/' exited with code: 127.

**Comment by kurtschelfthout** [comment]
Weird, I replaced that xcopy with an Msbuild thing in a later commit. Not sure why you still see it. Merge problem? Clearly xcopy is not cross platform 😄

**Comment by jhamm** [comment]
The Travis CI build is now fails when xunit is discovering tests for FsCheck.Tests for "Could not load type 'Xunit.Sdk.XunitTestFrameworkDiscoverer, xunit.execution.desktop'". When I run the xunit.console.exe locally on a windows machine it works, and the AppVeyor build succeeds. I will look into this further to see if I can reproduce this issue, then submit the fix.

**Comment by kurtschelfthout** [comment]
Cool. Progress :)

**Comment by jhamm** [comment]
From what I can see, this is an issue (The full story is here: xunit #158) that has been fixed in mono. They are just waiting for the [next release](https://github.com/xunit/xunit/issues/158#issuecomment-104660773).

**Comment by kurtschelfthout** [comment]
Man, this is throwing up a lot of bugs everywhere eh. Thanks for looking into it.

**Comment by kurtschelfthout** [comment]
Heads up - I transferred the repo to fscheck/fscheck (from fsharp/fscheck). If you want to keep updating this PR (which I encourage you to!) you'll need to update your remote.

**Comment by jhamm** [comment]
It still seems like the mono fix for xunit has not yet made it into a release.

**Comment by kurtschelfthout** [comment]
Pardon my confusion, what's the mono fix?

**Comment by jhamm** [comment]
Sure, here is the xunit issue that describes what is happening on mono: xunit/xunit#158 "xunit 2.0 TypeLoadException on Mono"

Quote from the xunit issue:

xunit 1.9.2 runs fine on current mono builds (on OSX), but xunit 2.0.0-beta fails on startup when running either xunit.console.exe or the xunit MSBuild task, with the same error:  
````System.TypeLoadException: Could not load type 'Xunit.Sdk.XunitTestFrameworkDiscoverer, xunit.execution, Version=2.0.0.2700, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'.````

[The latest comment](https://github.com/xunit/xunit/issues/158#issuecomment-114565915):
For those waiting for news on the fix for this, I've just been doing some testing. In the latest alpha release of Mono (4.0.2) this is not fixed, however in the latest nightly of Mono (4.3.0) this is fixed.

**Comment by kurtschelfthout** [comment]
Cool, thanks for the explanation. Guess we play the waiting game...

**Comment by jhamm** [comment]
The tests are now working fine on windows.

The Travis-CI build is failing for the xunit 2 TypeLoad Exception on Mono.

**Comment by slav** [comment]
Thanks for the hard work! Slight update to the code to support TestOutputHelper and use Timer provided by Xunit. Updated code for target inside PropertyTestCase.RunAsync. Replace ```sw``` with ```let timer = ExecutionTimer()```. This doesn't seem to be perfect and I'm guessing doesn't handle parallel execution very well. But it seems to work so far.

```
                    let target =
                        constructorArguments |>
                            Array.tryFind (fun x -> x :? TestOutputHelper) |>
                            Option.iter (fun x -> (x :?> TestOutputHelper).Initialize(messageBus,test))

                        let testClass=this.TestMethod.TestClass.Class.ToRuntimeType()
                        
                        if this.TestMethod.TestClass <> null && not this.TestMethod.Method.IsStatic then
                            Some (test.CreateTestClass(testClass, constructorArguments, messageBus, timer, cancellationTokenSource))
                        else None

                    Check.Method(config, runMethod, ?target=target)

                    match xunitRunner.Result with
                          | TestResult.True _ ->
                            (0, new TestPassed(test, timer.Total, (Runner.onFinishedToString "" xunitRunner.Result)) :> TestResultMessage)
                          | TestResult.Exhausted testdata ->
                            summary.Failed <- summary.Failed + 1
                            (1, upcast new TestFailed(test, timer.Total, (sprintf "%s%s" Environment.NewLine (Runner.onFinishedToString "" xunitRunner.Result)), new PropertyFailedException(xunitRunner.Result)))
                          | TestResult.False (testdata, originalArgs, shrunkArgs, Outcome.Exception e, seed)  ->
                            let message = sprintf "%s%s" Environment.NewLine (Runner.onFailureToString "" testdata originalArgs shrunkArgs seed)
                            (1, upcast new TestFailed(test, timer.Total, message, new PropertyFailedException(message, e)))
                          | TestResult.False (testdata, originalArgs, shrunkArgs, outcome, seed)  ->
                            summary.Failed <- summary.Failed + 1
                            (1, upcast new TestFailed(test, timer.Total, (sprintf "%s%s" Environment.NewLine (Runner.onFinishedToString "" xunitRunner.Result)), new PropertyFailedException(xunitRunner.Result)))
```

**Comment by jhamm** [comment]
Thanks that is a great suggestion. It definitely looks better than what was there. I will add your changes on the next push.

**Comment by jhamm** [comment]
It looks like the '-noappdomain' flag worked on mono!

Please let me know if there are any other changes that should be made.

@kurtschelfthout, thanks for being responsive with comments and suggestions!

**Comment by kurtschelfthout** [comment]
Very cool. 

Did you intentionally not use http://fsharp.github.io/FAKE/apidocs/fake-testing-xunit2.html or did you miss the comment in the issue thread perhaps?

**Comment by jhamm** [comment]
Yes, I should have indicated that I looked at the XUnit2Params from the link above and did not see where to specify the -noappdomain flag. With the adding the fsx file, we can get this working on mono asap.

**Comment by kurtschelfthout** [comment]
Oh, I see, my mistake. I saw the shadow copy setting and thought it was that. Thanks for clarifying.

**Comment by kurtschelfthout** [comment]
This is now in the xunit2 branch. I had some issues running FsCheck's tests because xunit2 runs classes in parallel by default, and FsCheck can't handle that. I'll try look into fixing that, meanwhile I added some attribute so xunit does not do that.

**Pull request closed without merging**
