### PR TITLE
FAKE has target "CI" on Travis

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by sideeffffect** [comment]
This error
```
System.Exception: Error during NuGet package creation. /home/travis/build/fscheck/FsCheck/packages/NuGet.CommandLine/tools/NuGet.exe pack -Version 2.1.1 -OutputDirectory "/home/travis/build/fscheck/FsCheck/bin" "FsCheck.2.1.1.nuspec"    
Directory '/home/travis/build/fscheck/FsCheck/NuGet/..\' not found.
```
is really strange. is this an issue with FsCheck, FAKE or NuGet?

**Comment by kurtschelfthout** [comment]
It is weird. My guess would be fake or nuget. Don't think we build that path in the build script ourselves. 

I finally see what you mean with the #I though.

**Comment by sideeffffect** [comment]
do you know who could we ask for help? would @forki know?

**Comment by kurtschelfthout** [comment]
I think it's worth opening an issue on the FAKE repo in the first instance. The NuGet folder is where the nuspec files are. Unfortunately the error is not very clear, I looked a bit at the source code of NuGetHelper.fs in FAKE but couldn't really figure out what is going on. Also, when I try to run on mono locally, it fails at an earlier instance (can't find xunit.console.exe, although it is there...these linux/windows path and case issues are maddening... :( )

**Comment by sideeffffect** [comment]
reported https://github.com/fsharp/FAKE/issues/975

**Comment by forki** [comment]
What happens when

**Comment by sideeffffect** [comment]
```
 ./build.sh CI
...
Starting Target: NuGet (==> RunTests)
Creating .nuspec file at /home/ondra/Projects/FsCheck/NuGet/FsCheck.2.1.1.nuspec
Created nuspec file /home/ondra/Projects/FsCheck/NuGet/FsCheck.2.1.1.nuspec
mono  /home/ondra/Projects/FsCheck/packages/NuGet.CommandLine/tools/NuGet.exe pack -Version 2.1.1 -OutputDirectory "/home/ondra/Projects/FsCheck/bin" "FsCheck.2.1.1.nuspec"    
Running build failed.
Error:
System.Exception: Error during NuGet package creation. /home/ondra/Projects/FsCheck/packages/NuGet.CommandLine/tools/NuGet.exe pack -Version 2.1.1 -OutputDirectory "/home/ondra/Projects/FsCheck/bin" "FsCheck.2.1.1.nuspec"    
Directory '/home/ondra/Projects/FsCheck/NuGet/..\' not found.
  at Fake.NuGetHelper.NuGet (Microsoft.FSharp.Core.FSharpFunc`2 setParams, System.String nuspecOrProjectFile) [0x00000] in <filename unknown>:0 
  at FSI_0001.Build+clo@202-15.Invoke (FSI_0001.ProjectInfo package) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Collections.SeqModule.Iterate[ProjectInfo] (Microsoft.FSharp.Core.FSharpFunc`2 action, IEnumerable`1 source) [0x00000] in <filename unknown>:0 
  at FSI_0001.Build+clo@201-14.Invoke (Microsoft.FSharp.Core.Unit _arg8) [0x00000] in <filename unknown>:0 
  at Fake.TargetHelper+targetFromTemplate@195[Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00000] in <filename unknown>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetTemplate`1 target) [0x00000] in <filename unknown>:0 
```

```
 mono /home/ondra/Projects/FsCheck/packages/NuGet.CommandLine/tools/NuGet.exe pack -Version 2.1.1 -OutputDirectory "/home/ondra/Projects/FsCheck/bin" "FsCheck.2.1.1.nuspec"
Attempting to build package from 'FsCheck.2.1.1.nuspec'.
Could not find file "/home/ondra/Projects/FsCheck/FsCheck.2.1.1.nuspec".
```

```
 find . -name FsCheck.2.1.1.nuspec
./NuGet/FsCheck.2.1.1.nuspec
```

btw this issues is quite similar to that one I'm fighting over here: https://github.com/fsprojects/FSharpx.Extras/pull/330

**Comment by forki** [comment]
please try to upgrade to FAKE 4.5.4 - I tried to work around it.

**Comment by kurtschelfthout** [comment]
@sideeffffect I upgraded FAKE on main, can you try merging from main to this PR so we can check?

**Comment by sideeffffect** [comment]
[FAKE 4.5.6 didn't seem to help](https://travis-ci.org/fscheck/FsCheck/builds/84971959#L1963)

**Comment by kurtschelfthout** [comment]
Changing the backslashes in the nuspec to forward slashes didn't help either. All out of ideas...

**Comment by sideeffffect** [comment]
we need to know where is that string coming from. @forki is it possible to debug FAKE?

**Comment by forki** [comment]
Actually my strategy in such nuget / mono issues to move to paket. There
are  too many quirks...
On Oct 12, 2015 9:57 PM, "Ondra Pelech" <notifications@github.com> wrote:

we need to know where is that string coming from. @forki
<https://github.com/forki> is it possible to debug FAKE?

—
Reply to this email directly or view it on GitHub
<https://github.com/fscheck/FsCheck/pull/166#issuecomment-147503730>.

**Comment by sideeffffect** [comment]
but FsCheck already uses Paket, no?

**Comment by forki** [comment]
Yes but not for pack and push.

**Comment by kurtschelfthout** [comment]
Ok, we should do that. Another day, another nuget annoyance. 

Should be another pull though, I'd like to keep this one open meanwhile.

**Comment by sideeffffect** [comment]
being solved in https://github.com/fscheck/FsCheck/pull/170

**Pull request closed without merging**
