### PR TITLE
Format test code according to 'Arrange, Act, and Assert' heuristic

### LINKED ISSUE #163: Make the property-based tests easier to read
Now that we use Unquote (which is great!), we could make the property-based tests easier to read.

As @ploeh wrote in #162:

>With the built-in operators `=!` and `<>!`, the assertions become so terse that they almost 'drown' in the test. If we stick with these operators, I would recommend adopting this heuristic for formatting tests: http://blog.ploeh.dk/2013/06/24/a-heuristic-for-formatting-code-according-to-the-aaa-pattern

I could happily send a Pull Request during the next couple of days, if you'd like to follow this direction.

### PR DESCRIPTION
**Pull request by moodmosaic**
This Pull Request resolves #163, by adopting [this](http://blog.ploeh.dk/2013/06/24/a-heuristic-for-formatting-code-according-to-the-aaa-pattern) useful heuristic for formatting tests.

Each commit log's message contains information regarding the motivation of each particular formatting.

### CODE REVIEW

**Comment by ploeh** [comment]
Looks good to me :+1:

**Comment by kurtschelfthout** [comment]
Can you do me a favour and squash this in a single commit?

**Comment by moodmosaic** [comment]
The commit messages may look similar, but they are not identical.

If I squash all in a single commit, the *exact* reasoning behind each change will get lost. For example, the message of e1320db is different than e968858, and so on.

**Comment by kurtschelfthout** [comment]
I'm fine with losing the exact reasoning.

**Comment by moodmosaic** [comment]
Sorry, but I wouldn't like to move forward in the way you propose :disappointed: – In my opinion, the reasoning behind each change matters here, as we're following a heuristic.

You're the maintainer of this codebase, so I won't push further, thus I'll just go ahead and close this...

Thanks for you time!

**Pull request closed without merging**
