### PR TITLE
Gen.Frequency Xml Comments

### PR DESCRIPTION
**Pull request by MarcoMaar**
PR related to #252

Changed the xml comments of frequency to use xml tags and added them to the overloaded methods.

### CODE REVIEW

**Comment by MarcoMaar** [comment]
maybe we should change the parameter in
https://github.com/fscheck/FsCheck/pull/262/files#diff-cf424f2bdbcba155096e701a72328711R211
to weightedValue to fit the other functions
https://github.com/fscheck/FsCheck/pull/262/files#diff-cf424f2bdbcba155096e701a72328711R233

**Comment by kurtschelfthout** [comment]
No, don't think that's worth changing. 2-tuples are fine.

**Comment by MarcoMaar** [comment]
I just meant the name of the parameter. It is "xs" in the first function and "weightedValues" in the other 3. But, yeah isn't a big deal I guess.

**Comment by kurtschelfthout** [comment]
Oh, I see, I misunderstood. Yes, though even `weightedValues` is probably a bad name.Because they're generators, not values. Maybe `frequencies` would be better...

**Comment by MarcoMaar** [comment]
I was thinking of changing the name to `weightedGenerators`, since I also used it in the comments. Then I started thinking about the names and looked up some definitions...

`frequencies` and `weightedGenerators` are not entirely correct I think. `frequency` is the number of times an event occurs. Therefore there should not be a generator within it. `weightedValue` is the product between the value and the weight. `WeightAndGenerators` would therefore be closer to correct since no calculation was performed.

There is also the record type `WeightAndValue<'a>' with `Value : 'a`. I think it would be more clear to change it to `WeightAndGenerator<'a>' with `Generator: 'Gen<a>` but this would be a breaking change.

I would leave `WeightAndValue<'a>' as it is, since it is breaking. I would change the parameters to `weightedGenerators`. Even though it is not 100% correct it transmits what the parameter will be used for.

Sorry, if you feel like I am wasting our time with unimportant details let me know and I will not focus on them that much.

**Comment by kurtschelfthout** [comment]
Well, perhaps we're over-thinking it a bit :) I don't think it's worth a breaking change at this point, but we could change it on the 3.0 branch. But  to be honest I think I introduced that type before C# had tuples, I think by now we should just use tuples as arguments for C#.

**Pull request merged**
