### PR TITLE
Added Comments to better explain C# Tests

### PR DESCRIPTION
**Pull request by SpocWeb**
Hi while trying to understand your C# Examples I added some Comments to better explain them. I think they would be helpful for the next reader. 
Personally I would have loved to see such brief explanations, especially in sample code.

### CODE REVIEW

**Comment by SpocWeb** [comment]
AppVeyor build fails, because only .NET 3.1.202  is available not 3.1.101 as specified in global.json. Should I change that?

**Comment by kurtschelfthout** [comment]
This happens too regularly :) yes feel free to update the global.json

Consider adding     `"rollForward": "latestMajor"` as described in  https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x so we don't run into this again. (I can do it in a separate commit too, but while you're there. Up to you.)

Thanks for the comments!

**Comment by SpocWeb** [comment]
OK I upgraded the Version and added the "rollForward": "latestMajor" Section, let's see whether it builds.

**Comment by kurtschelfthout** [comment]
Ok, travis has an issue but I'll sort that out on my end.

Thanks!

**Comment by SpocWeb** [comment]
travis-ci doesn't seem to run. Can you please look into that?

**Pull request merged**
