### PR TITLE
Minor spelling fixes

### PR DESCRIPTION
**Pull request by Kharacternyk**

### CODE REVIEW

**Comment by Kharacternyk** [comment]
I'm not sure whether these changes should be merged into master or any other branch

**Comment by kurtschelfthout** [comment]
Thanks very much - but can you rebase this on master please, as I merge master back to fscheck3 every so often and the other way around is not ready yet.

**Comment by Kharacternyk** [comment]
Of course

**Comment by kurtschelfthout** [comment]
Thanks. I really love this PR by the way, great that you've taken the time to go through and correct all these.

**Comment by Kharacternyk** [comment]
It seems that a lot of comments are just completely different in master compared to fscheck3. So it isn't much sense to make rebase. I may create new branch with fixes in master. Should I? Because that fixes are unnecessary if blocks of comments disappear in release

**Comment by kurtschelfthout** [comment]
I see. Ok, I'll just merge this and deal with any fallout later.

Thanks again!

**Comment by Kharacternyk** [comment]
Thanks! Sorry for the possible problems in future.

**Pull request merged**
