### PR TITLE
Documented and provided examples for Gen.constant.

### PR DESCRIPTION
**Pull request by ploeh**
This is another pull request related to #218. I know I start with all the boring, simple stuff, but I think it's important to establish a foundation for more complex examples.

### CODE REVIEW

**Comment by kurtschelfthout** [comment]
Cool stuff. Maybe I'm starting to agree with @moodmosaic in that the `1000` size is a bit confusing. And maybe we shouldn't be repeating the `10` either. 

Perhaps for now it's a good idea to add a short, perhaps incomplete explanation at the beginning with a ref to where size is more properly explained, and define a helper function `let sample = Gen.sample 1000 10` (or however) at the beginning that is used where appropriate?

**Comment by ploeh** [comment]
I agree that better explanation about the use of `Gen.sample` is warranted. As a start, I've submitted #240.

I'd also like to document the size number, but I'm not even sure that `1000` is the appropriate number. I simply selected it because `FsCheck.Test.Helpers.sample` use `1000` as the hard-coded size constant. To be honest, I find it a bit high, but I admit that my understanding of exactly how the various generators use the size is still hazy.

I'll be happy to add more information about that particular number (or another number), but for now, I don't know what to write, more than that it's a nice-looking, arbitrary number.

When it comes to defining a helper function, I'd suggest keeping each example as self-contained as possible. As the list of examples grow, a reader will have to jump around in the document in order to figure out how a hypothetical `sample` function is defined. If each example is self-contained, on the other hand, it's immediately clear what's going on, once you understand what `Gen.sample` does.

**Comment by kurtschelfthout** [comment]
Perhaps you should use `-1` for the examples where the size doesn't matter to make things clear. I.e. all the examples you've done so far. :)

**Comment by moodmosaic** [comment]
A negative size would make things more complicated. In v3, `sample` should better *not* take `size` at all, as proposed in #236.

**Comment by ploeh** [comment]
> Perhaps you should use -1 for the examples where the size doesn't matter to make things clear.

Whatever makes it easier to understand the documentation, I'm all for it :smile: 

The difficult part of writing documentation, however, is that you're often blind while doing it. I don't know how to measure which way to present the information is best.

I'm not fixed on the number `10,000`, but I'm concerned that `-1` would be confusing. On the one hand, it does demonstrate that the number doesn't really matter. On the other hand, for someone not yet fully understanding what FsCheck is, it may be confusing: _how can_ size _be negative?!_

As @moodmosaic points out in #236 removing `size` from `Gen.sample` would make the API more intuitive (in my opinion), but I don't know whether or not it's feasible.

**Comment by kurtschelfthout** [comment]
How about `0`? I'll reply on the other conversation about removing size from `sample`, but in any case that's a breaking change so it doesn't help us now.

My opinion on the whole size thing is that we explain it early or at least mention it as you've done. Sure there are a few of the simpler generator constructors that don't use size, but it's the minority. So as you've discovered with list, quite quickly you have to go into this topic anyway.

Distribution and size of generated values are important, too many people are overlooking it, and it's counter-productive imo to want to "hide" important things for newcomers because it puts them on the wrong track. Either they'll never understand and their use of FsCheck is severely crippled, or they'll be frustrated later when they find out that their nice property tests were in fact spending 99% of the time generating empty lists. At the risk of sounding grandiose, it's like trying to explain quantum mechanics without going into the particle/wave duality because it's "too confusing". You can't really understand things without understanding that.

**Pull request merged**
