### PR TITLE
Add Gen.scale to avoid some boilerplate code.

### PR DESCRIPTION
**Pull request by Kharacternyk**
Inspired by the Scalacheck one.

### CODE REVIEW

**Comment by Kharacternyk** [comment]
An example of usage: if I want to generate the couples of integers to represent a height and a width of some type of a game board, the count of squares on board will increase as size^2 by default. To avoid this, the following code might be used:
```f#
let board1 =
    (fun n -> Gen.resize (n |> float |> sqrt |> int) Arb.generate<int>)
    |> Gen.sized 
    |> Gen.two
```
and now it looks like this:
```f#
let board2 =
    Gen.scale (float >> sqrt >> int) Arb.generate<int>
    |> Gen.two
```

**Comment by Kharacternyk** [comment]
If the idea isn't rejected, I'll write the xml docs, some more tests and maybe some "overloads" for list, etc.

**Comment by kurtschelfthout** [comment]
I think that's a good idea, maybe call it `scaleSize` so it's clear what is being scaled.

> maybe some "overloads" for list, 

I don't understand that, why would you need additional overloads?

**Comment by Kharacternyk** [comment]
> I don't understand that, why would you need additional overloads?

I mean something like `Gen.scaleList` which require a list of sizes as an argument. Also we may provide `Gen.scaleSize2` of signature `(int -> int * int -> int) -> (Gen * Gen) -> Gen<a, a>`

**Comment by kurtschelfthout** [comment]
> It's a bit controversial, though. New API is good but defining a function that would be used only few times by users is redundant. That's why I haven't added all of the above yet. Thoughts?

Yeah I agree - don't think any more overloads pass the bar.

**Comment by kurtschelfthout** [comment]
This looks ready to merge then?

**Comment by Kharacternyk** [comment]
Yeah, I think so.

**Pull request merged**
