### PR TITLE
Migrate to paket

### PR DESCRIPTION
**Pull request by sideeffffect**
WIP

### CODE REVIEW

**Comment by sideeffffect** [comment]
we're getting
```
mono  /home/travis/build/fscheck/FsCheck/.paket/paket.exe pack output ../../bin/PaketPack  version  2.1.1 templatefile  paket.template
Paket version 2.15.1.0
Paket failed with:
	Could not find file "/home/travis/build/fscheck/FsCheck/paket.template".
```
it seems like Paket is ignoring the [`WorkingDir` parameter](https://github.com/fscheck/FsCheck/pull/170/files#diff-6074983490330a0aac1bd23c958232d7R212)
this is most likely the bug https://github.com/fsharp/FAKE/issues/792

@forki (or anybody who knows his way around Paket) can I kindly ask you for help with this?

**Comment by forki** [comment]
Sure. Will take a look

**Comment by forki** [comment]
https://github.com/fscheck/FsCheck/pull/171 seems to work, but you should verify that the packages are ok

**Comment by sideeffffect** [comment]
wow, I just wanted to help with the `WorkingDir` bug (so was it even a bug?), but you did rest of the work for me :smiley_cat:
thank you! let's hope everything is OK and @kurtschelfthout will be happy with this

**Comment by forki** [comment]
yeah I fixed the workingdir bug as an intermeadiate step.

2015-10-19 17:55 GMT+02:00 Ondra Pelech <notifications@github.com>:

**Comment by kurtschelfthout** [comment]
Thanks folks! I'm going to close this one given it's obsoleted by #171 (let me know if I've misunderstood)

**Comment by forki** [comment]
cool. but please check if the generated packages are ok. I didn't look into these changes here.

**Comment by kurtschelfthout** [comment]
Ok, will check.

**Pull request closed without merging**
