### PR TITLE
Standardize docs in Arb.Default (#492).

### PR DESCRIPTION
**Pull request by Kharacternyk**

### CODE REVIEW

**Comment by Kharacternyk** [comment]
Woah, looks like github thinks I wrote all of the TestData.fsx. What I've done wrong?

**Comment by kurtschelfthout** [comment]
Yes, weird. It looks like it thinks you added it. Did you mark it for add somehow?

**Comment by Kharacternyk** [comment]
>  Did you mark it for add somehow?

I'm not sure I understand. Is this file not tracked by git? I've added a paragraph to the docs but it seems I've done it a wrong way. If so how to do it properly?

**Comment by kurtschelfthout** [comment]
I don't know how it happened. Perhaps putting the changes on a stash and then try to re-apply them?

**Comment by Kharacternyk** [comment]
I did the exact things I had done before but via cmd instead of via Visual Studio and it works now. Closing it, #497 is a fixed version of it.

**Comment by Kharacternyk** [comment]
Interesting that this is reproducable. I just can't do this right via VS. Looks like a bug.

**Pull request closed without merging**
